### ISSUE TITLE
Non-integer diffusion time?

### ISSUE THREAD

**Issue by Rainshiney** [KrishnaswamyLab/MAGIC#124]
I'm in need of a diffusion time <1 but the function only takes integer input. Is there a work around for this?

**Comment by dburkhardt** [comment]
Currently, MAGIC is only defined for integer steps of diffusion time, which is why you're getting an error. We've used fractional matrix powers for generating animations of MAGIC with increasing `t`, but practically, we only use integer values of diffusion time in our research.

Out of curiosity, why do you want a diffusion time of <1?

**Comment by Rainshiney** [comment]
I'm getting over-smoothed output from magic. I'm working with a small subset of data (~150 cells), which is presumabely why the smallest t still gives over-smoothed results. 

Any suggestions on approaching this?

**Comment by dburkhardt** [comment]
Yes, this is too small of a population to accurately impute values. How many cells do you have total? Why are you looking at such a small subset? Have you tried running [PHATE](https://github.com/KrishnaswamyLab/PHATE) on your data? What does it look like?

Without knowing more, my suggestion is to run MAGIC on all of your data combined (ideally >1000 cells), then subset the data afterwards if you want to look at such a small population.

**Comment by Rainshiney** [comment]
Thanks for the suggestion, will run with that!

**Comment by dburkhardt** [comment]
Great, I'll close this issue for now. You're welcome to join our lab's new Slack Help here: https://www.krishnaswamylab.org/get-help
