### ISSUE TITLE
Test data

### ISSUE THREAD

**Issue by nbanovich** [KrishnaswamyLab/MAGIC#13]
Hi, is there any way you could provide a small test data set?

**Comment by dvdijk** [comment]
we plan to do that at some point, however for now I recommend using data that is already available online, such as one of the 10x datasets. This is a bone marrow dataset:
https://support.10xgenomics.com/single-cell/datasets/frozen_bmmc_healthy_donor2
download this file: "Gene / cell matrix (filtered)"
let us know if 10x data import works

**Comment by dvdijk** [comment]
I just saw that 10x data loading is not yet working. We'll fix this in the next days.

**Comment by pkathail** [comment]
Have just added 10x data loading in the python code as well.

**Comment by dvdijk** [comment]
10x provides several datasets:
https://support.10xgenomics.com/single-cell/datasets/
download "Gene / cell matrix (filtered)"
in the near future we'll also provide our data

**Comment by Pierre-Migeon** [comment]
could you provide example command line code for loading 10X data? Thanks

**Comment by nbanovich** [comment]
Honestly I only tried to run this a few times without success. I didn't
keep any of the code.

**Comment by Pierre-Migeon** [comment]
Is it possible to load 10x data? In the gui, there doesn't seem to be an
option for loading mtx files. Were you able to
run magic.mg.SCData.from_mtx? I do not know the correct usage for this
function in particular.

Thanks for the help!

**Comment by pkathail** [comment]
Hi!
We have implemented two methods to load 10x data, in both the command line tool and GUI. You can load 10x data with the command `scdata = magic.mg.SCData.from_10x(data_dir)` where data_dir is a directory that contains matrix.mtx, genes.tsv, and barcodes.tsv files. 
You can also load 10x data as an HDF5 file, using the command `scdata = magic.mg.SCData.from_10x_HDF5(HDF5file, genome)`
In the gui, both of these options are under the 'File' toolbar, 'File --> load 10x file' and 'File --> load 10x HDF5 file'
If you don't see these options, I'd suggested pulling the most recent updates from the master branch. If it still doesn't seem to be working, please let me know. Hope this helps!

**Comment by Pierre-Migeon** [comment]
Hi!

Thanks for the help- I was able to use the magic.mg.SCData.from_10x command
without problems, and have also been able to load data using the GUI. Much
of the example vignette works downstream of that, although I am having
trouble replicating the scatter plots with this data.

-P

**Comment by Pierre-Migeon** [comment]
Hi,

If you don't mind, I have another question (If you'd rather I post on the
forum, let me know). Here goes:

When I try to graph the magic genes in the tsne clusters using the function
"scdata.plot_gene_expression", I receive an error message warning that
these genes are not in the dataset. Unlike the tutorial, something about my
data requires me to use the ensemble gene name. When I run the
"scdata.magic.scatter_gene_expression" I do not get this problem, for
instance:


*fig, ax = scdata.magic.scatter_gene_expression(['MAGIC
ENSMUSG00000026728', 'MAGIC ENSMUSG00000000303'], color='MAGIC
ENSMUSG00000024238')*

runs fine. In addition, this command runs without error:


*fig, ax = scdata.plot_gene_expression(genes=['ENSMUSG00000024238'])*

It is only once I add the MAGIC prefix that this command stops working.

Any thoughts?
Thanks!
Pierre

**Comment by pkathail** [comment]
Hi Pierre,

In your example above, the MAGIC-ed version of the count matrix is stored in the object scdata.magic, while the original version of the count matrix is stored in the object scdata. When calling scdata.plot_gene_expression(), scdata can only access the original version of the count matrix. This difference can be seen in cells 6 & 7 of the [tutorial notebook](https://github.com/pkathail/magic/blob/develop/notebooks/Magic_single_cell_RNAseq.ipynb).

To color tSNE (done on the original count matrix) by the original gene expression values:
`fig, ax = scdata.plot_gene_expression(genes=['CDH1', 'VIM', 'FN1', 'ZEB1'])`

To color tSNE (done on the original count matrix) by the MAGIC-ed gene expression values, you can use a dictionary containing the new MAGIC-ed gene expression values:
`colors = {'MAGIC CDH1': scdata.magic.data['MAGIC CDH1'],
          'MAGIC VIM': scdata.magic.data['MAGIC VIM'],
          'MAGIC FN1': scdata.magic.data['MAGIC FN1'],
          'MAGIC ZEB1': scdata.magic.data['MAGIC ZEB1']}
fix, ax = scdata.plot_gene_expression(genes=colors)`

We've structured the data in this way so that users can continue to do further analyses (PCA, tSNE, etc.) on the MAGIC-ed data as well.

**Comment by Pierre-Migeon** [comment]
Perfect, that did the trick. Thanks again for the help! I'm impressed with
how rapidly MAGIC runs, but I'll have to throw a lot more computational
resources for downstream analysis since the output csv is ~6 GB.

-Pierre
