### ISSUE TITLE
Input matrix contains unexpressed genes

### ISSUE THREAD

**Issue by MichaelPeibo** [KrishnaswamyLab/MAGIC#132]
Hi, MAGIC team,

I got an issue when I run magic `magic_op.fit_transform(mda_data, genes=['VIM','FOXA2','EN1'])`
it gave me this error:

> Calculating MAGIC...
Using precomputed graph and diffusion operator...
Calculated MAGIC in 5.18 seconds.
/Users/peiboxu/.local/lib/python3.6/site-packages/magic/magic.py:358: UserWarning: Input matrix contains unexpressed genes. Please remove them prior to running MAGIC.
  warnings.warn("Input matrix contains unexpressed genes. "

Plus, I am loading the dataset by `mda_data=magic.io.load_10X('/Users/peiboxu/Desktop/mch_day50_filtered_gene_bc_matrices/GRCh38',
                           sparse=False, gene_labels='symbol', allow_duplicates=None)`

I am confused whether there is some error based on my dataset

**Comment by scottgigante** [comment]
Hi @MichaelPeibo ,

In gene expression data, if we have a column containing only zeroes, then we definitely can't gain anything by analyzing it - best thing to do is simply to remove it (with, for example,[`mda_data = scprep.filter.remove_empty_genes(mda_data)`](https://scprep.readthedocs.io/en/stable/reference.html#scprep.filter.remove_empty_genes)). It probably won't negatively affect your analysis by leaving it there, but it's possible that it could, which is why we include the warning.

**Comment by MichaelPeibo** [comment]
Hi @scottgigante ,

Thanks for help, it works by your suggestion!

It turns out I am not familiar with `scprep` package for preprocessing  and I just followed MAGIC tutorial...

**Comment by scottgigante** [comment]
Not a problem! The `scprep` package is rather new - I will include it in the tutorials at some point in the future. Hopefully you find it useful.
