### ISSUE TITLE
negative values exist in the output

### ISSUE THREAD

**Issue by HHHit** [KrishnaswamyLab/MAGIC#145]
In the preprocessing, I normalized the read count based on the library size and then log transform the whole matrix. Next, I input the matrix into MAGIC following the tutorials to obtain the whole smooth matrix. However, in the output, there are some negative values.The input is a 22k x 9k matrix (nsamples x ngenes) with no negative values.
Based on my understanding of the method, the cell-cell affinity matrix is multiplied multiple times, which should not induce in negative values. Has anyone met this issue before? Thanks,

**Comment by dvdijk** [comment]
this is because MAGIC is done in the PCA space, for scalability
so after MAGIC the imputed data (imputed PCs) are projected back to the original space and as a result there can be (very small) negative values
You can confirm that these are indeed very close to zero
you can do 3 things:
1) ignore, since they are very close to zero
2) set them to zero
3) run MAGIC on the original space so not on the PCA, which will be slow for bigger data

**Comment by HHHit** [comment]
These values are indeed close to zero. And it some time can generate all positive values, I guess there might be some randomness underneath it, right?
Thanks,
