### ISSUE TITLE
meaning of parameters

### ISSUE THREAD

**Issue by mfrancesconi81** [KrishnaswamyLab/MAGIC#19]
Hi, 
I'm trying to understand the meaning of the parameters. 
While I understand n_pca_components and t, I don't get which is the ka mentioned in the paper, is it knn or knn_autotune? Also, what is epsilon?

Thanks!

M.

**Comment by dvdijk** [comment]
ka is knn_autotune
epsilon is the standard deviation of the kernel, if epsilon is 1 (default) this will be equal to the distance to the knn_autotune-th neihghbor

**Comment by mfrancesconi81** [comment]
Great!
Thanks!

M.

**Comment by kevin199011** [comment]
How can we determine the optimal t and ka? Thank you!

**Comment by dvdijk** [comment]
ka should be chosen to be as small as possible, but large enough to give a connected graph. I suggest picking it between 3 and 10. k will be 3 x ka.
We are working on adding our optimal t method to the code. For now I suggest starting at t=6 and then try increasing up to around 12. The smaller you pick ka the larger t should be.

**Comment by dpcook** [comment]
Hey there!
Just wondering if the package has any way of checking for a connected graph? Are there any sanity checks that you would frequently run (code greatly appreciated!) to check the quality of the imputation? I'm getting expected gene-gene structure, which is good sign, but don't know how it's doing beyond that.

**Comment by dvdijk** [comment]
we didnt include such function, but you can compute the eigenvectors (using eig or svd) of the diffusion operator (Markov matrix) and look at the first couple right eigenvectors. The number of right eigenvectors with eigenvalue 1 is the number of connected components. You thus want to see only one eigenvalue with value 1, the rest between 0 and 1. If you have more than one eigenvalue of value 1 then it means your graph has more than one connected component.
In matlab you can use eigs or svds and get only the firts 2 or 3 eigenvectors, which will be fast.

It's hard to check the quality of the imputation, since we're dealing with unsupervised learning.. Best is to check if the biology makes sense.
