### ISSUE TITLE
interactive 3d plots compatibility

### ISSUE THREAD

**Issue by cynthiazhou1005** [KrishnaswamyLab/MAGIC#61]
Dear Magic developer,

Any advice on how to make the 3d plots interactive (rotate) in ipytnb? or is it just impossible with Jupyter notebook?

Thanks a ton,
Wen

**Comment by pkathail** [comment]
I'm not familiar with this myself, but [this page](https://stackoverflow.com/questions/33436221/displaying-rotatable-3d-plots-in-ipython-or-ipython-notebook/33440743#33440743) may be helpful. It suggests using `%matplotlib notebook` instead of `%matplotlib inlin`e to get embedded interactive figures in the IPython notebook.
