### ISSUE TITLE
R Magic error in "Computing Kernel"

### ISSUE THREAD

**Issue by ShuonanChen** [KrishnaswamyLab/magic#68]
Hi Magic developers!

I kept running into the problem using R magic when it is `Computing Kernel`.
It gives error (please see the attached screenshot) : 
> Error in Q$i : $  operator is invalid for atomic vectors

What am I doing wrong? Any help would greatly appreciated.  Thank you so much!

![screen shot 2018-01-03 at 6 28 29 pm](https://user-images.githubusercontent.com/22083756/34580518-55e8043c-f15b-11e7-91f4-36b722777625.png)

**Comment by dpcook** [comment]
Hey!

It's a current issue in the code, trying to strip the i, j, and x summary variables off of a full matrix rather than a space matrix. Right now the code goes:
`W <- as.matrix(W)`
`W <- W + t(W)`
`Q <- summary(W)`

But summary() on a full matrix doesn't provide the i, j, and x. It has to be a summary() of a sparse matrix to get these.

Taking the source code into R, adding `W <- as(W, "sparseMatrix")` right after the symmetrize distance step: `W <- W + t(W)` gets past this issue. Or, if you make sure the "Matrix" package is loaded, I think the transpose function works on the sparse matrix

I've had some issues with the R code and haven't been able to reproduce results generated using the python function in R. Python results look fantastic though. I'm not sure exactly where things are different, but I'm hoping to dig into this a bit in the next week or two. I think it may have to do with the diffusion operator, but I don't know for sure. I'll throw up an issue/PR if I figure stuff out.

**Comment by ShuonanChen** [comment]
Thank you! 
I added `W <- as(W, "sparseMatrix")` as you suggested. It resolved the `Computing kernel` problem. However, there's another error in the following `Diffusing`, says:
> Error in W^t : non-numeric argument to binary operator

I think I loaded all the dependencies (FNN, Matrix, rsvd) manually (it didn't automatically load any of them for me). 

> Or, if you make sure the "Matrix" package is loaded, I think the transpose function works on the sparse matrix

So you are saying that as long as Matrix package is loaded, this step: `W <- W + t(W)` is already making `W` as a sparse matrix? Thank you !


Shuonan

**Comment by djchin25** [comment]
I hacked the W^t call so run_magic completes but i don't think the hack is correct (scroll down to the graphic):
https://github.com/pkathail/magic/issues/60

**Comment by dpcook** [comment]
Hey Shuonan,
Yeah, I had previously had issues transposing a sparse matrix, but in the last couple times I've gone through it, the script executes, so I'm assuming it worked. Maybe I didn't have a dependency (Matrix?) loaded originally.

And once again, even if the script executes, be cautious for now--I'm not sure the results are correct. @djchin25, the diffusion step is definitely W^t (and not W^t(W))--you can check out the matlab and python versions of the code and it's the same. The one thing I notice in the Compute Kernel step, and maybe @dvdijk or @pkathail could comment on it, is that the matlab code is: `s = [s./(epsilon^2); zeros(N,1)];` and the python code is `dists = np.append(dists/(epsilon ** 2), np.zeros(N))`, whereas the R code is just `s <- s / epsilon^2`

I've been meaning to take a look at what the zeros functions are doing and if something similar isn't needed in R. That's the only difference I can see between the scripts after a short glance.

**Comment by cimbusch** [comment]
Dear dpcook,

have you looked further if the fix in the R code produces similar output to the output data produced by the python command?

Cheers,
  Charles

**Comment by dpcook** [comment]
Hey Charles,

I haven't dug any deeper into the R implementation unfortunately. Since discovering [scanpy](https://github.com/theislab/scanpy), my scRNA-Seq pipeline has become a bit more python-centric, so I've just been using the python implementation of MAGIC lately. I'll post here if I find anything.

**Comment by nganvu** [comment]
I cleaned up the R code; everything should be working now.
