### ISSUE TITLE
How can I export the imputed/modified matrix?

### ISSUE THREAD

**Issue by ajitjohnson** [KrishnaswamyLab/magic#76]
Hi @dvdijk,

After running magic, how can I export the imputed matrix file (in python)? 
i.e. to convert the SCData file into a regular data frame?

Thank you,
Ajit.

**Comment by dpcook** [comment]
Hey @ajitjohnson,

You can access the expression matrix and save it out to a csv file with:

`mat = scdata.magic.data`
`mat.to_csv(path_or_buf="~/Data/etc/lmagic.matrix.csv")`

Hope this helps,

David

**Comment by ajitjohnson** [comment]
Thanks, @dpcook. Worked perfectly.

**Comment by mheskett** [comment]
```mat.to_csv(path_or_buf="~/Data/etc/lmagic.matrix.csv")```

At what state of normalization will this matrix be in?

**Comment by pkathail** [comment]
After doing `mat = scdata.magic.data` as in the example above, `mat` is a dataframe of the imputed data matrix, so saving it to a csv file will save the imputed version of the data (how it is normalized before this point depends on what normalization method you use).

However, saving the imputed data matrix in this way will include 'MAGIC' prepended to each gene name, as you mentioned in #83. Instead, you can use the `to_csv()` function from MAGIC instead of pandas. Here, that would be `scdata.magic.to_csv(filename)` instead of `scdata.magic.data.to_csv(path_or_buf=filename)`

**Comment by mheskett** [comment]
Thank you kindly
